[versions]
activityCompose = "1.11.0"
agp = "8.12.3"
appfunctions = "1.0.0-alpha04"
composeBom = "2025.09.01"
composeMaterial3 = "1.6.0-alpha02"
kotlin = "2.2.20"
ksp = "2.2.20-2.0.3"

[libraries]
# Compose
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

# Wear-specific
wear-compose-material3 = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "composeMaterial3" }
wear-compose-navigation = { group = "androidx.wear.compose", name = "compose-navigation", version.ref = "composeMaterial3" }

# App Functions Feature set
appfunctions = { module = "androidx.appfunctions:appfunctions", version.ref = "appfunctions" }
appfunctions-compiler = { module = "androidx.appfunctions:appfunctions-compiler", version.ref = "appfunctions" }
appfunctions-service = { module = "androidx.appfunctions:appfunctions-service", version.ref = "appfunctions" }

# Testing
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
